version: "3.8"


services:

  shop:
    image: dockware/dev:6.4.15.0
    container_name: shop
    volumes:
      - "../:/var/www/html/custom/plugins/NotificationCenter:cached"
      # exclude by using anonymous volumes
      - "/var/www/html/custom/plugins/NotificationCenter/.git/"
      - "/var/www/html/custom/plugins/NotificationCenter/vendor/"
      - "/var/www/html/custom/plugins/NotificationCenter/src/Resources/app/administration/node_modules/"
      - "/var/www/html/custom/plugins/NotificationCenter/src/Resources/app/storefront/node_modules/"
      - "/var/www/html/custom/plugins/NotificationCenter/tests/Cypress/"
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
      - "3306:3306"
    environment:
      - XDEBUG_ENABLED=0
      - SW_API_ACCESS_KEY=SWSCOVFSNKLBYUTKS1VSOEDGUQ